version: '3.8'

networks:
  default:

services:
  mariadb-adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080

  mariadb-docker-container:
    image: mariadb
    depends_on:
      - mariadb-adminer
    ports:
      - 3306:3306

  server-docker-container:
    container_name: skilljs_server
    depends_on:
      - mariadb-docker-container
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ./server/:/app
    networks:
      - default

  client-docker-container:
    container_name: skilljs_client
    depends_on:
      - server-docker-container
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./client/:/app-client
    stdin_open: true
    tty: true
    networks:
      - default
