version: '3.8'

networks:
  default:

services:
  mariadb-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mariadb-docker-container:
    image: mariadb
    depends_on:
      - mariadb-adminer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skilljs
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306

  app-docker-container:
    container_name: skilljs_server
    depends_on:
      - mariadb-docker-container
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./server/dist/:/app
    stdin_open: true
    tty: true
    networks:
      - default